name: RM_app
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - expat=2.6.4
  - libffi=3.4.4
  - libmpdec=4.0.0
  - openssl=3.0.15
  - pip=24.2
  - python=3.13.1
  - python_abi=3.13
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - vc=14.40
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - altair==5.5.0
      - attrs==24.3.0
      - blinker==1.9.0
      - cachetools==5.5.0
      - certifi==2024.12.14
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.1
      - cssselect2==0.7.0
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.55.3
      - gitdb==4.0.12
      - gitpython==3.1.44
      - idna==3.10
      - jinja2==3.1.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - narwhals==1.21.1
      - numpy==2.2.1
      - openpyxl==3.1.5
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - protobuf==5.29.3
      - pyarrow==18.1.0
      - pydeck==0.9.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - referencing==0.35.1
      - regex==2024.11.6
      - reportlab==4.2.5
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.22.3
      - scipy==1.15.0
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.41.1
      - svglib==1.5.1
      - tenacity==9.0.0
      - tinycss2==1.4.0
      - toml==0.10.2
      - tornado==6.4.2
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - watchdog==6.0.0
      - webencodings==0.5.1
      - xlsxwriter==3.2.0
      - zipfile36==0.1.3
